# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brunno Henrique de Souza
title: Senior software engineer
email: brunnohenrique.ti@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: Brunn0henrique
github_username:  brunnohenrique
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: brunno-henrique-souza-524b5221
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a senior ruby software engineer. I'm curious, helpful and dedicated to the team, to achieve the common goal.

  In addition to software development knowledge I also able to manage DB, analyse and improve processes, manage linux server, and learn fast.

  I am most skilled in: <mark>Ruby on rails</mark> back-end, <mark>Postgres</mark>, <mark>Heroku</mark>, <mark>Linux Server</mark>, <mark>Javascript</mark>, <mark>RESTFULL API</mark> and <mark>GraphQL</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SGC
        link: https://sgc.accelular.com.br/
        link_text: SGC
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tempo Telecom
        link: https://www.tempotelecom.com.br/
        link_text: tempotelecom.com.br
        sub_title: IT Manager
        caption: April 2013 - February 2015
        quote: >
          cell phone management system
        description: | # this will include new lines to allow paragraphs
            I led the team rebuilding an old software using ruby on rails, postgres and hosted at AWS. In this moment I was a IT manager and manager project.

            I analised the whole software and distribute the tasks among the devs, looking for the bests solutions. 

      - layout: right
        title: Tech Telecom
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Cofounder - Software engineer
        caption: July 2016 - Present
        quote: >
          cell phone management system
        description: | # this will include new lines to allow paragraphs
          Project in ruby on rails, hosted at Digital Ocean. It's a smaller software than <mark>SGC</mark>, but manage all the business rules. 
          There are a web crawling collecting informations about the lines at operator website.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: State University of Goiás
        caption: 2006 - 2009
        sub_title: Information systems
        quote: >
          The State University of Goiás (UEG) is a multicampi state public university located in the State of Goiás, Brazil.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
